In [3]:
import numpy as np

array1= np.array([1,2,3])
print(type(array1), array1.shape, array1.ndim)

array2= np.array([[1,2,3],
                 [2,3,4]])
print(type(array2), array2.shape, array2.ndim)

array3= np.array([[1,2,3]])
print(type(array3), array3.shape, array3.ndim)

<class 'numpy.ndarray'> (3,) 1
<class 'numpy.ndarray'> (2, 3) 2
<class 'numpy.ndarray'> (1, 3) 2


In [4]:
# dtype : ndarray 내의 데이터 타입을 나타내 줌(int, float, char, bool 등)

list1= [1,2,3]
print(type(list1))

array1= np.array(list1)
print(type(array1), array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'> [1 2 3] int32


In [6]:
# array 내에 원소 타입이 섞여 있는 경우, 더 큰 타입으로 변환된다

list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype) # 숫자형 원소가 문자형으로 변환

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype) # int형이 float 형으로 변환

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [8]:
array_int = np.array([1,2,3])
print(array_int, array_int.dtype)

# float 형태로 변환
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

# int32 타입으로 변환
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32
[1. 2. 3.] float64
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arange, zeros, ones 

In [9]:
# np.arange : range함수와 유사함.

sequence_array= np.arange(10)
print(sequence_array, sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9] int32 (10,)


In [11]:
# np.zeros : 0으로 채워서 지정해준 shape만큼의 array를 반환함.
# np.ones: np.zeros와 마찬가지로 1값을 채워줌.

zero_array= np.zeros((3,2), dtype='int32')
one_array= np.ones((3,2))

print(zero_array, zero_array.dtype, zero_array.shape)
print(one_array, one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]] int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]] float64 (3, 2)


## ndarray 차원, 크기 변경 reshape()

In [15]:
array1= np.arange(10)
array2= array1.reshape(2,5)
array3= array1.reshape(5,2)

print(array1)
print(array2)
print(array3)

array3= array1.reshape(4,3)
print(array3) # Error !-> 10개 원소를 4,3 shape으로 변경하기 어려움.

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
# -1 값을 넣어주면 알아서 자동변환됨. 호환가능하도록 변환해줌. 

array1= np.aragne(10)
array2= array1.reshape(-1, 5) # col=5에 맞춰 row를 변경해줌.
array3= array1.reshape(5, -1) # row=5에 맞춰 col을 변경해줌.

print(array2.shape, array3.shape)

In [18]:
array1= np.arange(8)
array2d = array1.reshape(-1,1) # 1차원 arr를 2차원 arr로 바꿔주기
array3d = array1.reshape((2,2,2)) # 1차원 arr를 3차원 arr로 바꿔주기
array3d_2 = array3d.reshape(-1,1) # 3d 형태 arr를 2차원 arr로 바꿔주기

print(array1.tolist(), array1.shape)
print(array2d.tolist(), array2d.shape)
print(array3d.tolist(), array3d.shape)
print(array3d_2.tolist(), array3d_2.shape)

[0, 1, 2, 3, 4, 5, 6, 7] (8,)
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)
--------------------------------
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]] (2, 2, 2)
[[0], [1], [2], [3], [4], [5], [6], [7]] (8, 1)


## 넘파이의 ndarray 데이터 세트 선택하기 - Indexing

In [22]:
### Indexing

array1= np.arange(start=1, stop=10)
print(array1, type(array1))

print(array1[2], array1[-1]) # 맨 뒤 값 가져오기 위해서는 -1 지정.

# ndarray 값 수정하기 
array1[0] = 9
array1[8] = 0
print(array1)

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
3 9
[9 2 3 4 5 6 7 8 0]


In [24]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

print(array2d)
print(array2d[0,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1


In [27]:
### slicing 

array1= np.arange(start=1, stop=10)
print(array1)

array3= array1[0:3] # index=0,1,2값 추출
print(array3, type(array3))

array4= array1[:3]
print(array4, type(array4))

array5= array1[3:]
print(array5, type(array5))

array6= array1[:] # 전체 다 나옴
print(array6, type(array6))

[1 2 3 4 5 6 7 8 9]
[1 2 3] <class 'numpy.ndarray'>
[1 2 3] <class 'numpy.ndarray'>
[4 5 6 7 8 9] <class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [29]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print(array2d[0:2,0:2])

print(array2d[0],array2d[0].shape ) # 1차원 ndarray 반환

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[1 2 3] (3,)


In [32]:
### 팬시 인덱싱 

print(array2d)

array4= array2d[[0,1], 2] # row에는 0,1 인덱스 번호를 추출하고, col은 2에 해당하는 인덱스 번호 추출.
print(array4.tolist())

array5= array2d[[0,1]] # (0,:) (1,:) : 즉 0,1 row 추출됨. 
print(array5.tolist()) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2 3]
 [4 5 6]]


In [37]:
### 불린 인덱싱

array1d= np.arange(start=1, stop=10)
print(array1d)

array2 = array1d > 5 # 불린값 지정
print(array2)

array3 = array1d[array1d > 5]
print(array3)

# 만약 index값을 주고 그것에 해당하는 값만 추출할 때
indexes= np.array([0,2,4,6])
array4= array1d[indexes]
print(array4)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
[1 3 5 7]


## 행렬의 정렬 - sort(), argsort()
- np.sort()
- np.argsort()

In [45]:
### 1차원에서의 정렬 

org_array=[3,1,9,5]
print(org_array)

sort_array = np.sort(org_array)
print(sort_array)
print(org_array)# np.sort()로는 original array가 변화하지 않는다.

sort_array1 = org_array.sort()
print(sort_array1) # myarray.sort()로는 array를 반환하진 않는다.
print(org_array) # original array를 정렬한다.

print("-------------------")

sort_array1_desc= np.sort(org_array)[::-1] #  decreasing 
print(sort_array1_desc)

sort_array1_desc_2= org_array.sort(reverse=True)
print(sort_array1_desc_2)
print(org_array)

### 즉 앞으로는 original.sort(reverse=True)를 활용하자

[3, 1, 9, 5]
[1 3 5 9]
[3, 1, 9, 5]
None
[1, 3, 5, 9]
-------------------
[9 5 3 1]
None
[9, 5, 3, 1]


In [47]:
### 2차원 이상의 행렬의 정렬

array2d = np.array([[8,12],
                   [7,1]])

array2d_sort_axis0 = np.sort(array2d, axis=0) # axis=0즉 row방향으로 정렬됨.
print(array2d_sort_axis0) 
    # row가 여러개라고 보고 각각을 정렬. 즉 (8,7)을 (7,8)로 정렬하고 (12,1)을 (1,12)로 정렬함

array2d_sort_axis1 = np.sort(array2d, axis=1)
print(array2d_sort_axis1)
    # col이 여러개라고 보고 각각을 정렬. 즉 (8,12)를 정렬해서 (8,12)로, (7,1)을 정렬해서 (1,7)로!
    

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [51]:
### argsort : 정렬된 행렬의 기존 index 반환하기 

org_array= np.array([3,1,9,5])
sort_indices= np.argsort(org_array)

print(org_array)
print(sort_indices) # 정렬 순서를 나타내는 값의 index 즉 1번째 index가 먼저, 0번째 index가 다음.... 
print(org_array[sort_indices]) # 해당 index값을 가져오기 위해서.

print("-------------------------")
# 역순 정렬을 위해서는
sort_indices_desc = np.argsort(org_array)[::-1]

print(org_array)
print(sort_indices_desc)
print(org_array[sort_indices_desc])


[3 1 9 5]
[1 0 3 2]
[1 3 5 9]
-------------------------
[3 1 9 5]
[2 3 0 1]
[9 5 3 1]


## 선형대수 연산 - 행렬 내적, 전치행렬 구하기

In [54]:
### np.dot : 행렬 내적( 행렬의 곱셈)

A= np.array([[1,2,3],
            [4,5,6]])
B= np.array([[7,8],
            [9,10],
            [11,12]])

dot_product= np.dot(A,B)
print(A.shape, B.shape, dot_product.shape) # (2x3) x (3x2) = (2x2)
print(dot_product)

(2, 3) (3, 2) (2, 2)
[[ 58  64]
 [139 154]]


In [56]:
### np.transpose : 전치행렬

A= np.array([[1,2,3],
            [4,5,6]])
transpose_A= np.transpose(A)
print(transpose_A)


[[1 4]
 [2 5]
 [3 6]]
