### SGD(Stochastic Gradient Descent) 
- matrix decomposition method
- R = P*Q -> Real R과 가깝도록(오류 최소화하여) 반복하여 P,Q 찾기 

#### Algorithm
- 1. P,Q 임의로 설정 
- 2. pred(R) = P*t(Q) -> Error= pred(R) - real(R) 
- 3. minimize(Error) -> update P,Q !!
- 4. 반복

- L2-norm Cost function은 아래와 같다.
   - min(sum(realR - P*t(Q))) + lambda(q^2 + p^2) 

In [10]:
import numpy as np

# R 생성, P,Q 초기화, K=3 으로 설정 
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN],
              [np.NaN, 5, np.NaN, 3,1],
              [np.NaN, np.NaN, 3,4,4],
              [5,2,1,2,np.NaN]])
num_users, num_items= R.shape
K=3 # 잠재요인의 차원 

print(num_users, num_items, K) # R은 4x4 행렬

np.random.seed(1)
P= np.random.normal(scale = 1./K, size = (num_users, K)) 
Q= np.random.normal(scale = 1./K, size = (num_items, K))
    # scale(표준편차) 디폴트 1 인데 1/K로 조정 
    # 행렬 size 지정(잠재요인 차원수를 col으로 맞춰줌)

print(P) 
print(Q)









4 5 3
[[ 0.54144845 -0.2039188  -0.17605725]
 [-0.35765621  0.28846921 -0.76717957]
 [ 0.58160392 -0.25373563  0.10634637]
 [-0.08312346  0.48736931 -0.68671357]]
[[-0.1074724  -0.12801812  0.37792315]
 [-0.36663042 -0.05747607 -0.29261947]
 [ 0.01407125  0.19427174 -0.36687306]
 [ 0.38157457  0.30053024  0.16749811]
 [ 0.30028532 -0.22790929 -0.04096341]]
